"""Create employees and email records tables

Revision ID: df338451d672
Revises: 28a281914f92
Create Date: 2026-01-03 13:39:23.599031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df338451d672'
down_revision = '28a281914f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('from_addr', sa.String(length=500), nullable=True),
    sa.Column('reply_to', sa.String(length=500), nullable=True),
    sa.Column('return_path', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('headers_text', sa.Text(), nullable=True),
    sa.Column('ingested_via', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)

    op.create_table('behavior_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('behavior_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavior_events_email_id'), ['email_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_events_employee_id'), ['employee_id'], unique=False)

    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=False),
    sa.Column('manipulation_strategy', sa.String(length=100), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_results_email_id'), ['email_id'], unique=False)

    op.drop_table('learners')
    op.drop_table('scenarios')
    op.drop_table('attempts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('learner_id', sa.INTEGER(), nullable=False),
    sa.Column('scenario_id', sa.INTEGER(), nullable=False),
    sa.Column('choice', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('hints_used', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('channel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=True),
    sa.Column('body_text', sa.TEXT(), nullable=False),
    sa.Column('attack_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('manipulation_strategy', sa.VARCHAR(length=100), nullable=False),
    sa.Column('difficulty', sa.INTEGER(), nullable=True),
    sa.Column('explanation_plain', sa.TEXT(), nullable=False),
    sa.Column('red_flags', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('experience_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_results_email_id'))

    op.drop_table('detection_results')
    with op.batch_alter_table('behavior_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavior_events_employee_id'))
        batch_op.drop_index(batch_op.f('ix_behavior_events_email_id'))

    op.drop_table('behavior_events')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_email'))

    op.drop_table('employees')
    op.drop_table('email_records')
    # ### end Alembic commands ###
